function [results] = trainClassifierSvm(trainingData, Trains, Tests)
   disp('Support Vector Machine Classification')
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A matrix with the same number of columns and data type
%       as the matrix imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a matrix containing only the predictor columns used for
% training. For details, enter:
%   trainedClassifier. HowToPredict
% Auto-generated by MATLAB on 13-Dec-2021 15:59:23


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
% Convert input to table

numFeatures = size(trainingData,2)-1;
   
    myNames = [1:numFeatures];
    names = cellstr(num2str(myNames'))';
    names2 = names;
    names{end+1} = 'Y';
    
    
inputTable = array2table(trainingData, 'VariableNames', names);

predictorNames = names2;
predictors = inputTable(:, predictorNames);
response = inputTable.Y;
isCategoricalPredictor(numFeatures) = false;
% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationSVM = fitcsvm(...
    predictors, ...
    response, ...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'KernelScale', 1, ...
    'BoxConstraint', 0.001002975245133279, ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);

% Create the result struct with predict function
predictorExtractionFcn = @(x) array2table(x, 'VariableNames', predictorNames);
ensemblePredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.ClassificationEnsemble = classificationSVM;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2021a.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new predictor column matrix, X, use: \n  yfit = c.predictFcn(X) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nX must contain exactly 358 columns because this model was trained using 358 predictors. \nX must contain only predictor columns in exactly the same order and format as your training \ndata. Do not include the response column or any columns you did not import into the app. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');
% 
% % Extract predictors and response
% % This code processes the data into the right shape for training the
% % model.
% % Convert input to table
% inputTable = array2table(trainingData, 'VariableNames', names);
% predictorNames = names;
% predictors = inputTable(:, predictorNames);
% response = inputTable.Y;
% isCategoricalPredictor(numFeatures) = false;
% % Set up holdout validation

trainingPredictors = predictors(Trains'==1, :);
trainingResponse = response(Trains'==1, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationSVM = fitcsvm(...
    trainingPredictors, ...
    trainingResponse, ...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'KernelScale', 1, ...
    'BoxConstraint', 0.001002975245133279, ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);

% Create the result struct with predict function
ensemblePredictFcn = @(x) predict(classificationSVM, x);
validationPredictFcn = @(x) ensemblePredictFcn(x);

% Add additional fields to the result struc

% Compute validation predictions
validationPredictors = predictors(Tests'==1, :); % features
validationResponse = response(Tests'==1, :); 
[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);
%validationPredictions % Resposta do classificador
validationResponse = validationResponse(:);
validationScores = validationScores(:,2);
% Compute validation accuracy
correctPredictions = (validationPredictions == validationResponse);
isMissing = isnan(validationResponse);
correctPredictions = correctPredictions(~isMissing);
% validationAccuracy = sum(correctPredictions)/length(correctPredictions);

[fpr,tpr,~,auc] = perfcurve(validationResponse, validationScores, 1 );

C = confusionmat(validationResponse, validationPredictions);
[val1, val2] = calculateMeasures(C, auc);
% val2
results = {val1, val2, fpr, tpr};
